name: PUB

on:
  release:
    types: [published]

jobs:
  binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x64
          - arm64
        node-version:
          - 14
        os:
          - linux
          - macos
          - win
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: npm install && npm run-script build
      - name: Package into node binary
        id: package
        uses: lando/pkg-action@v4.0.0
        with:
          config: package.json
          entrypoint: bin/run
          arch: ${{ matrix.arch }}
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}
          upload: false
      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.package.outputs.file }}
          asset_name: ${{ steps.package.outputs.artifact-key }}
          asset_content_type: application/zip
