name: PUB

on:
  push:
    tags:
      - 'v*'
jobs:
  binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x64
          - arm64
        node-version:
          - 14.x
        os:
          - linux
          - macos
          - win
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Package into node binary
        uses: lando/pkg-action@v2
        with:
          entrypoint: bin/run
          arch: ${{ matrix.arch }}
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}